resolver: lts-16.22
packages:
- ./auto-update
- ./mime-types
- ./wai
- ./wai-extra
- ./warp
- ./warp-tls
- ./wai-app-static
- ./wai-websockets
- ./wai-conduit

extra-deps:
- http2-2.0.0
- network-byte-order-0.1.1.0
- tls-1.5.3
- tls-session-manager-0.0.4

allow-newer: true

flags:
  wai-extra:
    build-example: true
nix:
  pure: false
  packages:
  - fcgi
  - zlib

image:
  containers:
    - base: "fpco/pid1"
      name: "yesodweb/warp"
      executables:
        - warp
